### ISSUE TITLE
Bad 

### ISSUE THREAD

**Issue by G9-dev-real** [pankoza-pl/Rutherfordium.exe#11]
Colmare is no skid and working

**Comment by pankoza-pl** [comment]
🗨️🤡

**Comment by Darik8Coder** [comment]
> 🗨️🤡

no @pankoza-pl my malwares are no skid and not trash delete this zip file g3tr3kt

**Comment by G9-dev-real** [comment]
> left_speech_bubbleclown_face

pankoza this c-l-o-w-n emoji is bad not actually me

**Comment by G9-dev-real** [comment]
@pankoza-pl is the biggest skid

**Comment by G9-dev-real** [comment]
:trollface:

**Comment by G9-dev-real** [comment]
[e]

**Comment by G9-dev-real** [comment]
> left_speech_bubbleclown_face

are you kidding me?
